name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Push build folder to Another Repo
      env:
        ANOTHER_REPO_TOKEN: ${{ secrets.ANOTHER_REPO_TOKEN }}
      run: |
        git clone https://github.com/<another-repo-link> another-repo
        cp -r build another-repo/build
        cd another-repo
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git commit -a -m $(git log -2 --pretty=%B)
        git push