name: Merge Job

on:
  push:
    branches:
      - main

jobs:
  merge_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Create build directory and files
        run: |
          mkdir build
          echo 'Hello world' > build/hello.txt
          mkdir build/error
          echo 'Hello Error' > build/error/error.txt
          tar -cvf build.tar build

      - name: Store build folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build.tar

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: .

      - name: Set up Git credentials
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          mkdir -p ~/.ssh
          echo "machine github.com login ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          chmod 600 ~/.netrc

      - name: Checkout repo_2 branch
        run: |
          git clone https://$GITHUB_TOKEN@github.com/neerajdhurandher/git-practice.git
          cd git-practice
          git checkout ${{ secrets.TARGET_BRANCH }}
          cp -r ../build/* .
          git add .
          git commit -m "Add build contents"
          git push https://$GITHUB_TOKEN@github.com/neerajdhurandher/git-practice.git HEAD:${{ secrets.TARGET_BRANCH }}
          